### ISSUE TITLE
Multiline formatting

### ISSUE THREAD

**Issue by Skoucail** [digitalmedia34/updateconfig#12]
We are having a problem when tools (visual studio, nuget, etc) auto format our web.config file.
Sometimes long appSettings or connectionStrings get split up into multi lines.
When this happens the task will not replace the value anymore. (If the enter is between the key/name en the value attribute.

I believe if you use this regex it should work:
`(?:"test")((?!>)[\s\S])*?(?:value="|connectionString=")(.*?)"`

**Comment by digitalmedia34** [comment]
Could you provide me with examples? So I can run tests

**Comment by Skoucail** [comment]
> Could you provide me with examples? So I can run tests

Basicly if you have section below in your web/app.config.
The plugin wil replace Value1 and Value3. But not Value2.
Because "Key2" and Value= aren't on the same line.

`<appSettings>`
    `<add key="Key1" value="Value1" />`
    `<add key="Key2" `
     ` value="Value2" />`
    `<add key="Key3" value="Value3" />`
`</appSettings>`

**Comment by digitalmedia34** [comment]
Oh I see, yeah I noticed that too. The problem is that the engine doesn't like lookaheads so I had a hard time. Your suggested regex doesn't work, any other idea?

**Comment by digitalmedia34** [comment]
Think i found a solution looking at your regex. Thanks will make the change

**Comment by Skoucail** [comment]
Ok thanks for looking at it.
And reverting the production version regex.
Little panic here when nothing got replaced anymore in production :o

**Comment by digitalmedia34** [comment]
Get latest extension, I just published an update

**Comment by Skoucail** [comment]
> Get latest extension, I just published an update

I already downloaded version 1.4.2
I'm just a bit concerned about the new regex without the lookahead (due to unsupported reasons).

I will give a example.
If you create a web.config file. With in the service endpoints section a entry with attribute name="default".
Under the service endpoints there is a appSettings section with various entries.

Now if you have a variable with name default. I think the first value in the appSettings will be replaced. Tho the appSettings key="NotDefault".
