### ISSUE TITLE
Version 1.4.0 NOT working

### ISSUE THREAD

**Issue by Skoucail** [digitalmedia34/updateconfig#13]
Server: Azure DevOps server 2019
Update config version: 1.4.0

The just released version 1.4.0 doesn't replace any config settings.
In the logs i see it still matches my config files.
```
2019-08-23T13:10:49.6159568Z ##[debug]2 matches
2019-08-23T13:10:49.6187239Z ##[debug]2 final results
```

It still loops trough all variables
```
2019-08-23T13:21:33.4580383Z ##[debug]Variable name: xxx
```

But it doesn't log/find any matches.

**Comment by digitalmedia34** [comment]
Its version 1.4.2

**Comment by Skoucail** [comment]
> Its version 1.4.2

Yea but versions 1.4.0 - 1.4.1 also got pushed to everyone that installed the plugin.
But versions 1.4.1 and 1.4.2 work again. Thx!
