### ISSUE TITLE
config keys containing a part of another one, makes replacement incorrect

### ISSUE THREAD

**Issue by santo2** [digitalmedia34/updateconfig#2]
Hi, I have the following issue:

I have two connectionstrings:
- Connectionstring
- ConnectionString.XXX

since that "ConnectionString.XXX" also contains "ConnectionString", it now replaces both with the value of "ConnectionString".

**Comment by digitalmedia34** [comment]
Hi I just recently found the same issue and have a fix that I'm testing.

**Comment by digitalmedia34** [comment]
Hi @santo2 , I published an updated version, the new version is 1.2.3. I ran a test with your example and it works. Update your extension and let me know

**Comment by santo2** [comment]
Thanks!
