### ISSUE TITLE
Cannot seem to install extension v 1.2.3 in VSTS/visualstudio.com

### ISSUE THREAD

**Issue by michaelharrod** [digitalmedia34/updateconfig#3]
Hello. First off thanks very much for writing this extension, it's a real help to us.

We also have the key matching problem raised in [issue #2](https://github.com/digitalmedia34/updateconfig/issues/2#issue-340165938) and we seem to be unable in install the fixed version in our VSTS cloud instance.

Whenever we add the task, we get v 1.2.2. I've asked our VSTS administrator if he can update it but doesn't appear to show an update available or allow an explicit update. He removed and re-installed it, but we're still at 1.2.2.

![image](https://user-images.githubusercontent.com/8508216/43867492-9dafa146-9bbd-11e8-8361-9822e7663cfd.png)

Any thoughts on how we can get the update?

**Comment by digitalmedia34** [comment]
I really don't know, the only thing I can think of is that is cached somehow. Try removing the extension from the server (which you did) and the build/release task. I checked the published version is right

![image](https://user-images.githubusercontent.com/5529666/43870677-b507f8e2-9b46-11e8-8496-4a82edb20548.png)

Sorry I cant be much of a help
