### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by ghost** [digitalmedia34/updateconfig#4]
Hello,

I have this in my appsettings in my app.config file:

`<appSettings>
    <add key="EndPointApplicationUrl" value="http://testserver/application" />
  </appSettings>`

And I have specified in my team build in the page "variables" a variable with Name EndPointApplicationUrl and Value "http://google.com".
But nothing gets replaced.

I left all properties on default... (except the display name)

**Comment by digitalmedia34** [comment]
Hi I just ran a test and it seems to be working fine for me.  This is what my test looks like
![image](https://user-images.githubusercontent.com/5529666/45230222-393df380-b296-11e8-9f1b-446469548500.png)

Here is the result:
![image](https://user-images.githubusercontent.com/5529666/45230250-507ce100-b296-11e8-87bb-d61f9bae61bd.png)

This is what it looks like in teamservices:
![image](https://user-images.githubusercontent.com/5529666/45230298-6d191900-b296-11e8-9ad8-5e1cd26526aa.png)

**Comment by digitalmedia34** [comment]
My only guess its the formatting of your test

**Comment by ghost** [comment]
hello,

I have the same, but nothing happens.
How do you configure the build task?

**Comment by digitalmedia34** [comment]
There really is no configuration

![image](https://user-images.githubusercontent.com/5529666/45295562-219c8000-b4cd-11e8-8828-e62ad6b91233.png)

**Comment by ghost** [comment]
I got it working!
My build task was too low in the sequence. It was doing the replacement on my original config after I already copied them to a file share.
It works, thanks

**Comment by digitalmedia34** [comment]
Great
