### ISSUE TITLE
replaces the app settings key, not the value

### ISSUE THREAD

**Issue by santo2** [digitalmedia34/updateconfig#6]
I have set it to replace appsettings of a web config for a service fabric deployment.
root directory: $(System.DefaultWorkingDirectory)/PipelineTests/drop/applicationpackage
Target files: **/*.config

in the service fabric website app.config file:
 
`
<appSettings>
    <add key ="xxx" value="xxx"/>
    <add key="xxx.yyy" value="xxx.yyy"/>
  </appSettings>
`

in the variables: 
`
xxx --> newValueXXX
xxx.yyy --> newValueXXX.YYY
`
results in the app.config: applicationname.exe.config
`
  <appSettings>
    <add key="newValueXXX" value="xxx" />
    <add key="newValueXXX.YYY" value="xxx.yyy" />
  </appSettings>
`

**Comment by digitalmedia34** [comment]
Yes there is a limitation the key and the value cannot be the same.

**Comment by benrjm** [comment]
You should be able to use the token prefix and suffix to avoid this issue.
