### ISSUE TITLE
Matching VSTS variable name vs App Config key name

### ISSUE THREAD

**Issue by debashis1982** [digitalmedia34/updateconfig#7]
Looks like the task is not trying to match the variable name with the whole config key name. It is doing partial matches.
If there are two app settings in app.config like 
```

<add key="foo" value="bar"/>
<add key="fooxyz" value="barxyz"/>
```
and I have VSTS variables
```
foo --> abc
fooxyz --> abcbar

```
After running this task we can see that value for fooxyz is incorrectly replaced like so
```
<add key="foo" value="abc"/>
<add key="fooxyz" value="abc"/>
```

**Comment by digitalmedia34** [comment]
I could be wrong but you seem to have an extra space on fooxyz

**Comment by debashis1982** [comment]
> I could be wrong but you seem to have an extra space on fooxyz

No there is no extra space. I actually had to change the key name to something else to make it work.

**Comment by digitalmedia34** [comment]
question, by key name you mean foo ?

**Comment by debashis1982** [comment]
Yes foo and fooxyz are the two keys in the example. I had to change the key name fooxyz to something else in my App.config so that the VSTS variable set for variable name foo does not get set for the value corresponding to key name fooxyz in my App.config

**Comment by digitalmedia34** [comment]
I tried your example but I am not able to reproduce.

![image](https://user-images.githubusercontent.com/5529666/51748691-34c67b80-207b-11e9-9f50-a7dc00ee2441.png)

and here are my keys in teamservices

![image](https://user-images.githubusercontent.com/5529666/51748764-6c352800-207b-11e9-9de2-7f3ecd0441c5.png)

**Comment by debashis1982** [comment]
I am not sure if I am able to explain it properly but I am still seeing the issue. You can close it.
