### ISSUE TITLE
not working in azure devops

### ISSUE THREAD

**Issue by rcuzco** [digitalmedia34/updateconfig#9]
Hello.
I get this problem when using this task:

##[section]Starting: Update config variables
==============================================================================
Task         : Update config
Description  : Update config variables in files
Version      : 1.2.2
Author       : Digitalmedia34
Help         : [More Information](https://github.com/digitalmedia34/updateconfig#readme)
==============================================================================
**##[error]File not found: 'd:\a\_tasks\updateconfig_a0515ec8-6254-5ffd-932c-86772e2b5960\1.2.2\index.js'**
##[section]Finishing: Update config variables

**Comment by digitalmedia34** [comment]
That's an interesting error. I'll check it right now

**Comment by digitalmedia34** [comment]
I fixed the issue and uploaded an updated version. @rcuzco  check it out and let me know, the new version is 1.3.2

**Comment by rcuzco** [comment]
Great!!
It works!!!
Thank you very much!!!
